-- Таблица заказов
CREATE TABLE IF NOT EXISTS orders(

    sk INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- Суррогатный ключ
    id VARCHAR NOT NULL,                                 -- Номер закупки на сайте
    org_inn VARCHAR                                      -- ИНН компании-организатора
);

-- Таблица контрактов
CREATE TABLE IF NOT EXISTS contracts(

    sk INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- Суррогатный ключ
    id VARCHAR NOT NULL,                                 -- Номер контракта на сайте
    price DECIMAL(16, 2),                                -- Финальная цена
    suppl_inn VARCHAR,                                   -- ИНН компании-поставщика
    ord_id VARCHAR                                       -- Номер закупки на сайте
);

-- Таблица регионов Российской Федерации
CREATE TABLE IF NOT EXISTS regions(
	id INT PRIMARY KEY,									-- Главный ключ
	kod VARCHAR(2),										-- Код региона РФ
	name VARCHAR										-- Наименование региона РФ
);